### ISSUE TITLE
Mask =dev-libs/folks-0.11* ?

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#116]
… because it depends on `>=gnome-extra/evolution-data-server-3.13.90`, which is masked in vivid?

Best,
Bela

**Comment by shiznix** [comment]
Hi,

dev-libs/folks-0.11 should already be keyword masked.

**Comment by and3k** [comment]
I’m running ~amd64, so not for me ;)

**Comment by shiznix** [comment]
We could mask dev-libs/folks-0.11 in overlay but then this unleashes a larger maintenance/testing routine for us on all other future keyword masked package combinations.

Much easier for our sanity (and in some cases the system's) to assume a stable system with overlay built on top.

So I guess the short answer to the problem is that you will need to maintain your own custom maskings such as this when running global ~arch.

**Comment by and3k** [comment]
OK, no problem :)

**Comment by shiznix** [comment]
Apologies and3k, you were correct we should mask >=folks-0.11.
Have done so in commit cedfa86b7f4118bcb40686af10206ddec6cabc9b

Thanks :)

**Comment by and3k** [comment]
:) :+1:
