### ISSUE TITLE
Issues with new install.  Will help fix if I can

### ISSUE THREAD

**Issue by eyoung100** [shiznix/unity-gentoo#150]
## Issues ##

I know I helped out yesterday, because I really like this concept. Just because all my buddies give me crap for running a source based distribution, and I want to prove a point that I can make my system look exactly like anyone else's with a little work.  As such, I'd like to report a few bumps in the install road that I've run into:

1. `dev-libs/properties-cpp-0.0.1_p0_p01_p20140730` doesn't build.  It fails with, `*** No rule to make target gmock/libs/gtest/libgtest.a`
2. `x11-misc/appmenu-qt5-0.3.0_p0_p01_p20151130` fails because of a sandbox violation, `libappmenu-qt5.so and ./libappmenu-qt5.so are the same file`
3. `pdebbuild` is missing because `dev-util/pbuilder` entered last rites and was removed from the tree in Sept 2010.  See [the ChangeLog](https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/dev-util/pbuilder/ChangeLog?hideattic=0&view=log)

## Fixes ##

1. `dev-libs/properties-cpp-0.0.1_p0_p01_p20140730` will probably build once I upgrade compilers.  To do that properly, see [Upgrading GCC](https://wiki.gentoo.org/wiki/Upgrading_GCC).  You could probably do this in `unity-base/unity-build-env` and passing a custom USE flag, i.e., `upgrade-gcc`.  If set the upgrade should automatically occur, following the steps outlined in the link exactly, after downloading GCC5 from this repo.  As GCC5 becomes stable in the main tree, watch for updates.  I was at GCC 4.93, so 4.93 to 5.30 is a big jump.  As such, an elog should be provided before executing `emerge -uDNavt unity-meta`, so that the upgrade can be done manually.
2.  `x11-misc/appmenu-qt5-0.3.0_p0_p01_p20151130` ignores the `--prefix` option for some reason, but that I don't know how to fix, except for setting FEATURES="-sandbox" in `make.conf`, which is somewhat dangerous.
3.  If you'd like the unit test for pdebuild in CMake, you can add pbuilder from [pbuilder 0.223 source package in Ubuntu](https://launchpad.net/ubuntu/+source/pbuilder/0.223) to the repository as dev-util/pbuilder, or edit every CMake.txt file to remove the option.

## Why Am I Telling You This ##

As much flak as Unity receives, I like it, but the big distribution model bothers me.  As such, I'd like to help you maintain packages etc in this repository. Please let me know how I can help you...

**Comment by shiznix** [comment]
Hi @eyoung100 welcome, always good to see new energy come onboard :)

I still really love the Unity desktop and use it daily as my main desktop.
It stands well alone without the need to tie itself to any one distribution.

Walking through the points you raise:
1. dev-libs/properties-cpp failure wrt. gmock/gtest at first glance looks to be parallel make unsafe but we already set 'MAKEOPTS=-j1' - will need to see complete failing build.log for this one.
 Upgrading GCC is one of those special items on Gentoo that should remain un-automated due to GCC's ABI changes/breakages and possible gcc-config selection. We can however detect and error message if the minimum gcc version is not met to build Unity packages. This is done in the overlay's eclass/ubuntu-versionator.eclass
2. Can you provide a paste of the complete failing build.log for x11-misc/appmenu-qt5
3. While some builds will report that they can't find pdebuild/pbuilder during the build process they should not fail and as such pbuilder shouldn't be required.

If you'd like to become involved in maintaining and troubleshooting, most of the work happens over on IRC in Freenode's network at #unity-gentoo. Though we all seem to idle and come alive at different times due to the vastly different timezones and life hours ;)

**Comment by eyoung100** [comment]
Attached files as requested... kinda hard with no DE at the moment.  Thank goodness for wgetpaste.

[appmenu-qt5.txt](https://github.com/shiznix/unity-gentoo/files/440465/appmenu-qt5.txt)
[properties-cpp.txt](https://github.com/shiznix/unity-gentoo/files/440464/properties-cpp.txt)

The build failure for both occurred with `sys-devel/gcc-4.9.3:4.9.3::gentoo` set.  I have since switched compilers to `sys-devel/gcc-5.3.0:5.3.0::gentoo`, but am still in the process of upgrading packages via `revdep-rebuild`

**Comment by eyoung100** [comment]
## Update ##

1. `dev-libs/properties-cpp-0.0.1_p0_p01_p20140730` built after using `gcc-config` to set the new GCC5 compiler.  Also rebuilt all affected files using `revdep-rebuild`.
2.  `x11-misc/appmenu-qt5-0.3.0_p0_p01_p20151130` will build if `FEATERES="-sandbox -usersandbox"` is set in `make.conf`

## New Issue ##

1.  `x11-libs/gsettings-qt-0.1a_p0_p01_p20160329` errors out because the linker is missing the newly compiled library (itself).  See: 

[gsettings-qt.txt](https://github.com/shiznix/unity-gentoo/files/440862/gsettings-qt.txt)

A question for you though.  I'm using the `--skip-first` option to build as many as I can.  While I do, does having `-O3` set in `CFLAGS` affect any of these package building phases??  If so, I can downgrade the system to `-O2`...  Please keep this open, as I'll fix my own bug(s) after I get the overlay successfully compiled.

**Comment by eyoung100** [comment]
This ebuild works in my local overlay.  Remember to use the coverage penv file
[oxide-qt-1.16.5_p0_p00160401.txt](https://github.com/shiznix/unity-gentoo/files/461148/oxide-qt-1.16.5_p0_p00160401.txt)

**Comment by eyoung100** [comment]
All fixed
