### ISSUE TITLE
gnome 3.18 packages are getting removed from main tree

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#161]
Hi!

more and more of the gnome 3.18 packages are getting removed from main portage tree, and since 3.20 packages are masked by unity, this starts to break a lot of unity dependencies… any ideas how to fix that?

Thanks,
Bela

**Comment by shiznix** [comment]
Hi Bela,

Am fast tracking the Yakkety ebuilds into the overlay now.
Doing a build test now and all going well will drop Xenial and stabilise Yakkety.

**Comment by shiznix** [comment]
Well it took a little extra time due to the changes in Yakkety moving away from upstart and towards systemd to launch desktop sessions and services but I think everything should be working now.

If you haven't already, you're welcome to make the switch by switching to the 'yakkety' profile and give it a go.

**Comment by and3k** [comment]
Switching now…

**Comment by and3k** [comment]
All updates worked and everything running fine so far! Thanks! :)
