### ISSUE TITLE
Stability of Unity on Gentoo

### ISSUE THREAD

**Issue by Zohran** [shiznix/unity-gentoo#169]
Hello, sorry if sometimes i don't speak english very well, i'm french. I have question. Unity for gentoo is it clean or he use patched versions of many packages ? Is it a minimal installation or are there additional applications? Is it usable only with systemd?

**Comment by and3k** [comment]
Hi,

I’ve been using unity-gentoo for years now and I’m really happy with it. There were some hickups with unity not working, but mostly that’s my fault because I’m running a fully ~amd64 (i.e., testing) environment and that’s not supported. If you run a stable Gentoo you should be good.

You need systemd! And a lot of packages are patched and other are masked from the main tree. So if you want for example KDE and unity running on the same system that is a bit of a hassle, because there are always some minor dependency problems that need to be fixed.

There are USE flags, so you can choose if you want all bells and whistles or a minimal version.

Hope that helps,
Bela

**Comment by shiznix** [comment]
Hopefully that answers your question Zohran.
Closing this one now but feel free to open another issue if you encounter any problems.

Cheers :)
