### ISSUE TITLE
Be Prepared....

### ISSUE THREAD

**Issue by eyoung100** [shiznix/unity-gentoo#172]
See [CANONICAL SHUTS DOOR ON UNITY, UBUNTU PHONE AND CONVERGENCE](https://itsfoss.com/ubuntu-unity-shutdown/)

**Comment by shiznix** [comment]
Cheers @eyoung100 

Bit of a shame really but kind of inevitable with how developer progress has been tracking.
The financial side of the business was expecting Unity8 to be the default desktop 3 years ago.

Current state of the overlay is a wait and see approach as to whether the announcement of "dropping Unity and heading back to Gnome" actually means "sticking with Unity7" seeing as nearly all of it is actually Gnome aside from the compiz plugin that is the Unity shell.

Also worth noting that upon the announcement, most of the development team have already forked packages to allow development to continue.

**Comment by konfou** [comment]
>forked packages

I will point out the existence of @yunit-io's [Yunit](/yunit-io/yunit) and @UBports' [unity8](/ubports/unity8). If any of them picks up track you could probably use that as a source instead of Launchpad deprecated repos.

>sticking with Unity7

That will also be tricky as Unity7 is a Compiz plugin whereas GNOME has moved in using Mutter. So staying with Unity7 means they have to keep Compiz alive or port Unity7 to Mutter which needs lots of work as well.

**Comment by shiznix** [comment]
Thanks for the links to other Unity8 forks, but wouldn't hold my breath.

Unity8's progress was slow before but now it's been thrown out by Canonical to be mostly developed by the open source community, I imagine it's progress will now become glacial (hopefully I'm wrong).

Unity7 already handled Gnome's mutter move some years ago (2010-ish?) so they'd just need to maintain the status quo now rather than waste man hours on a pointless port.

**Comment by shiznix** [comment]
Closing this now, Mir and Unity8 have been dropped from the overlay as upstream development has ended. Perhaps into the future it can be revisited if the forks mature enough.
