### ISSUE TITLE
Ehooks discussion

### ISSUE THREAD

**Issue by shiznix** [shiznix/unity-gentoo#186]
Opening discussion for the implementation of ehooks here...

I haven't had a chance to try the new ehooks method of applying Ubuntu patches yet but have a couple of questions on maintaining them.

How do you version control Ubuntu patches using the ehooks method?

Ubuntu package versions often misalign with what is in main portage tree.
How do you ensure the Ubuntu patchset being applied via ehooks is for the correct version in the portage tree?

**Comment by c4pp4** [comment]
Ehooks are similar to user patches (https://wiki.gentoo.org/wiki//etc/portage/patches). Furthermore you can apply patches requiring eautoreconf or instead of patches you can theoretically use any command within any phase of build.

Ad versions:
Similar to user patches. Priority order is:
app-arch/file-roller-3.22.3-r0
app-arch/file-roller-3.22.3
app-arch/file-roller-3.22
app-arch/file-roller-3
app-arch/file-roller
plus slots. You can "blacklist" package version by creating empty dir.

Ad misalign:
Ehooks are not suitable for all cases.

I included some info in https://github.com/shiznix/unity-gentoo/blob/master/README_ebuild_hooks.txt or you can look at ready ehooks in /etc/ehooks or in unity-gentoo/profiles/<release>/ehooks.

**Comment by shiznix** [comment]
Awesome thanks!

So we use it as an alternative when we don't need to do version checking for maintenance or patch application.

A perfect example I guess would be the recent inclusion of www-client/firefox as an ehook where Gentoo's version always seems to align with Ubuntu's and applies only a very minimal patchset that also doesn't tend to vary much between versions.

**Comment by renegart** [comment]
would be nice to have a small description about the patches

**Comment by c4pp4** [comment]
'/etc/ehooks' have descriptions, you can use 'eselect ehooks notes' or 'eselect ehooks \<number>'

'unity-gentoo/profiles/\<release>/ehooks' have no descriptions, maybe they should be placed inside 'unity-gentoo/NOTES' file beside 'Reasons for patching/maintaining packages' section.

Maybe we should add some information about ehooks in '/unity-gentoo/metadata/news' as well.

**Comment by c4pp4** [comment]
@shiznix 
Suggestion:

Ebuild hooks ('ehooks') provide a way to additionally apply changes (patches, diffs, seds, triggers etc.) when installing packages.

There are two types of ehooks - system and optional.
1) System ehooks are always applied and are located in '/var/lib/layman/unity-gentoo/profiles/releases/${PROFILE_RELEASE}/ehooks'.
2) Optional ehooks are provided by 'unity-extra/ehooks' package and are located in '/etc/portage/ehooks'. You can use 'eselect ehooks notes' to see short information about them. They must be enabled through 'eselect ehooks' by selecting desired package. Such a package needs to be re-emerged then. 'eselect ehooks' config files are created in '/etc/portage/ehooks/conf.d'. Optional changes are primary taken from Ubuntu packages and are mainly related to application appearance. 

Additional informations about ehooks are located in:
/var/lib/layman/unity-gentoo/NOTES
/var/lib/layman/unity-gentoo/README_ebuild_hooks.txt

**Comment by shiznix** [comment]
We can probably close this off now, ehooks are great and they're working well :)

**Comment by c4pp4** [comment]
Any questions on recent changes?

**Comment by shiznix** [comment]
Looks good! :)
