### ISSUE TITLE
missing tray icon of Joplin-App

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#241]
*Joplin* is a Electron-based application. Since a few weeks it's tray-icon is missing. Seems there is something broken on the tray icon integration layer

**Comment by c4pp4** [comment]
Maybe it's related to 98e607d3172d9c7c03ab66ac3ece97579a92a7d4
Can you try to install eoan version?

**Comment by shiznix** [comment]
So I installed Joplin to reproduce this - it's a pretty neat app and yes same result here, enabling systray icon in it's settings and the icon is missing.
Seems Joplin's had some issues recently wrt. tray icon display problems so perhaps there has been a change to fix that has broken for other desktops? (noting it warns in it's Settings dialog that their systray icon doesn't work on all desktops).

Syslog throws some more light:
`indicator-application-service: Notification Item on object /StatusNotifierItem of org.kde.StatusNotifierItem-2334440-1 doesn't have enough properties`

And 'ps' confirms it's joplin causing the error:
`~ # ps a | grep 2334440`
`2334440 pts/2    Sl+    0:01 /opt/joplin/joplin`

Joplin is suffering from the same problem Quassel needing a patch to fix it's SNI tray icon (see profiles/ehooks/net-irc/quassel/files/SNI-systray_fix.patch).

Quassel was easy to patch, Joplin's way more convoluted because their broken implementation comes by way of Electron.

**Comment by renegart** [comment]
Meanwhile fixed by Joplin
